### ISSUE TITLE
备份采用频繁和备份监控的一致性

### ISSUE THREAD

**Issue by 77557231** [Grain-Yu/mysqld_exporter-0.15.0#8]
备份设置返回值0或者1判断是否成功。prometheus采样频率通常15s一次，只通过0/1可能在相当一段时间返回值都不会变。是否可能只在备份完成后返回备份成功。
例如返回值为0、1、2、-1 无备份为0，正在备份为1，备份成功为2，备份失败为-1.
这样可以更好判断备份成功失败和备份的时长。

**Comment by Grain-Yu** [comment]
Hi，
a.实际上，程序中判断逻辑是先判断/tmp/backupstatus.txt文件是否可读，不可读返回1000；
b.然后判断文件内容是否为1，是的话返回1；
c.其他情况返回0；
所以对于要细分备份异常情况的需求，建议进一步在执行备份的脚本里区分，如无备份在文件中写入2，正在备份在文件中写入3...对于这些值，都归属于上面exporter中的c类

**Comment by Grain-Yu** [comment]
> 备份设置返回值0或者1判断是否成功。prometheus采样频率通常15s一次，只通过0/1可能在相当一段时间返回值都不会变。是否可能只在备份完成后返回备份成功。 例如返回值为0、1、2、-1 无备份为0，正在备份为1，备份成功为2，备份失败为-1. 这样可以更好判断备份成功失败和备份的时长。


exporter的返回值还是简洁一些比较好，自定义需求放到备份脚本中。
